# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: debe397663c673a33437e637878a220bdc812bc872e787369da1608b199d73ee264576fe8d303bcc5fa08a90d87be9a042e991844f6ac34c52cf1a1b88d30ada

test:
  secret_key_base: f8bc1a141a88b095a1237860f6a9d16cfec081e2ca7fb573b21a5dc3fe91facec3dbb41e3257d7454835765d18a6c983cd470d2f598ee6a22108ba93cf9230ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
